version: "3.1"
services:
  canal_mysql:
    image: mysql
    container_name: canal_mysql
    ports:
      - 13306:3306
    # expose:
      # - 3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qweasd
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql_data:/var/lib/mysql
      # - ./mysql_logs:/var/lib/mysql
