version: "3.1"
services:
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes:
      - ./data:/data
    # command: /bin/bash -c "redis-server /data/redis.conf"
