version: '3.1'
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
    - /Volumes/To/repos/influxdb:/var/lib/influxdb
    - /Volumes/To/yakirdc/gatling/influxdb.conf:/etc/influxdb/influxdb.conf
  grafana:
   image: grafana/grafana
   ports:
     - 3000:3000
   environment:
     - GF_SERVER_ROOT_UR=http://127.0.0.1
     - GF_SECURITY_ADMIN_PASSWORD=qweasd
